### ISSUE TITLE
Fails to build with boost 1.75 on Mac

### ISSUE THREAD

**Issue by dreerr** [cyang-kth/fmm#178]
When trying to build fmm from the Repo the process fails because of boost 1.75

```
/usr/local/include/boost/geometry/util/type_traits_std.hpp:54:12: error: no
      template named 'conditional_t' in namespace 'std'; did you mean
      'conditional'?
    : std::conditional_t<Trait::value, conjunction<Traits...>, Trait>
      ~~~~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/type_traits:530:33: note: 
      'conditional' declared here
    struct _LIBCPP_TEMPLATE_VIS conditional {typedef _If type;};
```
[…]
```
/usr/local/include/boost/geometry/core/coordinate_dimension.hpp:101:23: error: 
      constexpr function's return type 'void' is not a literal type
constexpr inline void assert_dimension()
                      ^
```
[…]
```
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [CMakeFiles/ALGORITHM.dir/src/algorithm/geom_algorithm.cpp.o] Error 1
make[1]: *** [CMakeFiles/ALGORITHM.dir/all] Error 2
make: *** [all] Error 2
```

When I change the `CXX_FLAGS` from `-std=gnu++11` to `-std=gnu++14` it compiles successfully, but Python libs don't work because of `34105 segmentation fault  python`

**Comment by cyang-kth** [comment]
Perhaps you need to install older version of boost. 

https://travis-ci.org/github/cyang-kth/fmm/jobs/755993211
