### ISSUE TITLE
Make Error : OGRMultiLineString has no member named toUpperClass

### ISSUE THREAD

**Issue by xunhs** [cyang-kth/fmm#51]
**Describe the bug**
Hi,
Thanks for your amazing map matching tools. I tried to install requirements and C++ program as your tutorials in window 10 with wsl2. After I installed requirements I tried to run cmake, but it appears to a error as followed:
`OGRMultiLineString has no member named toUpperClass`
Would you please help me why this error appears and how to figure out it? 
Thank you very much :)

**Expected behavior**

**Screenshots**
![图片](https://user-images.githubusercontent.com/31309468/76824973-98999e00-6853-11ea-8d37-939633cf4393.png)

**Comment by xunhs** [comment]
P.S., `After I installed requirements I tried to run make,` installed of `cmake`

**Comment by cyang-kth** [comment]
@xunhs 

The problem seems to be with the library of GDAL. 

You need to check the output of 

```
mkdir build
cd build
cmake ..
```  
It will print out the version of the libraries found.

**Comment by xunhs** [comment]
Yeah, I checked it and the output lists as follow:
```
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found GDAL: /usr/lib/libgdal.so (Required is at least version "2.2")
-- GDAL headers found at /usr/include/gdal
-- GDAL library found at /usr/lib/libgdal.so
-- Boost 1.54.0 found.
-- Found Boost components:
   serialization
-- Boost headers found at
-- Boost library found at Boost::serialization
-- Found OpenMP_C: -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- OpenMP_CXX_LIBRARIES found at /usr/lib/gcc/x86_64-linux-gnu/7/libgomp.so;/usr/lib/x86_64-linux-gnu/libpthread.so
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/d/Workspace/TrajEmbedding/Environments/fmm-master/build
```
it seems to have no wrong issues. You mean the version of GDAL is not above 2.2?

**Comment by xunhs** [comment]
![图片](https://user-images.githubusercontent.com/31309468/76849898-3fe0fa00-6881-11ea-8114-59fcafc4a83c.png)
Em... I think the version of GDAL is not wrong.

**Comment by cyang-kth** [comment]
@xunhs 

According to the error, it still seems to be the version is not correct. 
Can you check me the code of this file in your system?

```
head /usr/include/gdal/ogr_geometry.h
```

In my computer it shows something like this

```
/******************************************************************************
 * $Id: ogr_geometry.h 967fd78f12996d9faa39a977a2b93547b10db65b 2018-10-14 20:02:24 +0200 Even Rouault $
 *
 * Project:  OpenGIS Simple Features Reference Implementation
 * Purpose:  Classes for manipulating simple features that is not specific
 *           to a particular interface technology.
 * Author:   Frank Warmerdam, warmerdam@pobox.com
 *
 ******************************************************************************
 * Copyright (c) 1999, Frank Warmerdam
```

If possible, also this file

```
tail /usr/include/gdal/gdal_version.h
```
On my side, it shows
```
#ifndef GDAL_RELEASE_NAME
#  define GDAL_RELEASE_NAME     "2.4.1"
#endif
```

**Comment by xunhs** [comment]
Yeah.  The outputs of above codes is as bellow:
- `head /usr/include/gdal/ogr_geometry.h`
```
/******************************************************************************
 * $Id: ogr_geometry.h 967fd78f12996d9faa39a977a2b93547b10db65b 2018-10-14 20:02:24 +0200 Even Rouault $
 *
 * Project:  OpenGIS Simple Features Reference Implementation
 * Purpose:  Classes for manipulating simple features that is not specific
 *           to a particular interface technology.
 * Author:   Frank Warmerdam, warmerdam@pobox.com
 *
 ******************************************************************************
 * Copyright (c) 1999, Frank Warmerdam
```

- `tail /usr/include/gdal/gdal_version.h`
```
#endif

#if !defined(DO_NOT_DEFINE_GDAL_RELEASE_DATE_AND_GDAL_RELEASE_NAME)
#ifndef GDAL_RELEASE_DATE
#  define GDAL_RELEASE_DATE     20190628
#endif
#ifndef GDAL_RELEASE_NAME
#  define GDAL_RELEASE_NAME     "2.4.2"
#endif
#endif
```

**Comment by xunhs** [comment]
Well, I tried to only `Install python extension ` referred as your tutorials and it seems succeed. But I failed to run the fmm_test.py and  `import fmm`.
```
>>> import os, sys
>>> current_path = os.getcwd() + '/build'
>>> current_path
'/mnt/d/Workspace/TrajEmbedding/Environments/fmm-master/python/build'
>>> sys.path.append(current_path)
>>> import fmm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/d/Workspace/TrajEmbedding/Environments/fmm-master/python/build/fmm.py", line 17, in <module>
    _fmm = swig_import_helper()
  File "/mnt/d/Workspace/TrajEmbedding/Environments/fmm-master/python/build/fmm.py", line 16, in swig_import_helper
    return importlib.import_module('_fmm')
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: /mnt/d/Workspace/TrajEmbedding/Environments/fmm-master/python/build/_fmm.so: undefined symbol: _ZTIN5boost7archive6detail14basic_iarchiveE
```

**Comment by cyang-kth** [comment]
@xunhs 

How did you run the make to compile?

```
mkdir build
cd build
cmake  -G "Unix Makefiles" ..
make
```

I am not sure if it is the problem of wsl or not.

**Comment by xunhs** [comment]
I tried to run both `cmake ..` and `cmake  -G "Unix Makefiles" ..` in wsl and cwgin and all failed.. Running in cwgin spent much time so I tried to build in wsl2 :(

**Comment by cyang-kth** [comment]
@xunhs 

According to your error, it is the problem that OGRMultiLineString does not contain a method toUpperClass.

From the official site of GDAL, I found that this method is added in version 2.3. In GDAL 2.2 there is no such a method. 

Version 2.3

https://github.com/OSGeo/gdal/blob/b6677ad469cdff677778fb43be49125f281f9dbc/gdal/ogr/ogr_geometry.h#L2783-L2785

Version 2.2

https://github.com/OSGeo/gdal/blob/5e4967f05ecf5043d5266b4f8eb0c3868ba40a95/gdal/ogr/ogr_geometry.h#L1692-L1715

It implies that your make still build with the dependency of 2.2, which happens to be your ogrinfo version (2.2.3).

I am not quite sure about the reason of it.  Maybe I should fix the version inconsistency. The method itself is not stated as added in version 2.3 in the original documentation of GDAL.

**Comment by xunhs** [comment]
Yeah. Thank you for your quick response and valuable answers. Next I want to try it in real Ubuntu system instead of wsl.  Installing Python interface for fmm seems to be successful without the above C++ building. Now I try to `import fmm` in the python codes.
Thanks for your help, you save my life too :)

**Comment by cyang-kth** [comment]
@xunhs 

I have pushed a patch to avoid using this method. 
https://github.com/cyang-kth/fmm/commit/4e6bba2fa8707cf6967decf5e2a12467e6984ec1
You can try to download the latest version of the repo and try to build it again.

**Comment by xunhs** [comment]
@cyang-kth 

:<  A new error appeared with the latest version.

```
...

CMakeFiles/fmm_omp.dir/app/fmm_omp.cpp.o: In function `void boost::serialization::throw_exception<boost::archive::archive_exception>(boost::archive::archive_exception const&)':
fmm_omp.cpp:(.text._ZN5boost13serialization15throw_exceptionINS_7archive17archive_exceptionEEEvRKT_[_ZN5boost13serialization15throw_exceptionINS_7archive17archive_exceptionEEEvRKT_]+0x1d): undefined reference to `boost::archive::archive_exception::archive_exception(boost::archive::archive_exception const&)'
fmm_omp.cpp:(.text._ZN5boost13serialization15throw_exceptionINS_7archive17archive_exceptionEEEvRKT_[_ZN5boost13serialization15throw_exceptionINS_7archive17archive_exceptionEEEvRKT_]+0x24): undefined reference to `boost::archive::archive_exception::~archive_exception()'
fmm_omp.cpp:(.text._ZN5boost13serialization15throw_exceptionINS_7archive17archive_exceptionEEEvRKT_[_ZN5boost13serialization15throw_exceptionINS_7archive17archive_exceptionEEEvRKT_]+0x2b): undefined reference to `typeinfo for boost::archive::archive_exception'
CMakeFiles/fmm_omp.dir/app/fmm_omp.cpp.o: In function `boost::archive::basic_binary_iprimitive<boost::archive::binary_iarchive, char, std::char_traits<char> >::load_binary(void*, unsigned long)':
fmm_omp.cpp:(.text._ZN5boost7archive23basic_binary_iprimitiveINS0_15binary_iarchiveEcSt11char_traitsIcEE11load_binaryEPvm[_ZN5boost7archive23basic_binary_iprimitiveINS0_15binary_iarchiveEcSt11char_traitsIcEE11load_binaryEPvm]+0x5a): undefined reference to `boost::archive::archive_exception::archive_exception(boost::archive::archive_exception::exception_code, char const*, char const*)'
fmm_omp.cpp:(.text._ZN5boost7archive23basic_binary_iprimitiveINS0_15binary_iarchiveEcSt11char_traitsIcEE11load_binaryEPvm[_ZN5boost7archive23basic_binary_iprimitiveINS0_15binary_iarchiveEcSt11char_traitsIcEE11load_binaryEPvm]+0x6d): undefined reference to `boost::archive::archive_exception::~archive_exception()'
CMakeFiles/fmm_omp.dir/app/fmm_omp.cpp.o: In function `boost::archive::basic_binary_iprimitive<boost::archive::binary_iarchive, char, std::char_traits<char> >::load_binary(void*, unsigned long) [clone .constprop.2161]':
fmm_omp.cpp:(.text._ZN5boost7archive23basic_binary_iprimitiveINS0_15binary_iarchiveEcSt11char_traitsIcEE11load_binaryEPvm.constprop.2161[_ZN5boost7archive6detail15common_iarchiveINS0_15binary_iarchiveEE5vloadERNS0_12version_typeE]+0x5d): undefined reference to `boost::archive::archive_exception::archive_exception(boost::archive::archive_exception::exception_code, char const*, char const*)'
fmm_omp.cpp:(.text._ZN5boost7archive23basic_binary_iprimitiveINS0_15binary_iarchiveEcSt11char_traitsIcEE11load_binaryEPvm.constprop.2161[_ZN5boost7archive6detail15common_iarchiveINS0_15binary_iarchiveEE5vloadERNS0_12version_typeE]+0x70): undefined reference to `boost::archive::archive_exception::~archive_exception()'
CMakeFiles/fmm_omp.dir/app/fmm_omp.cpp.o: In function `boost::archive::detail::common_iarchive<boost::archive::binary_iarchive>::vload(boost::archive::version_type&)':
fmm_omp.cpp:(.text._ZN5boost7archive6detail15common_iarchiveINS0_15binary_iarchiveEE5vloadERNS0_12version_typeE[_ZN5boost7archive6detail15common_iarchiveINS0_15binary_iarchiveEE5vloadERNS0_12version_typeE]+0x25): undefined reference to `boost::archive::detail::basic_iarchive::get_library_version() const'
CMakeFiles/fmm_omp.dir/app/fmm_omp.cpp.o: In function `boost::archive::detail::common_iarchive<boost::archive::binary_iarchive>::vload(boost::archive::tracking_type&)':
fmm_omp.cpp:(.text._ZN5boost7archive6detail15common_iarchiveINS0_15binary_iarchiveEE5vloadERNS0_13tracking_typeE[_ZN5boost7archive6detail15common_iarchiveINS0_15binary_iarchiveEE5vloadERNS0_13tracking_typeE]+0x5e): undefined reference to `boost::archive::archive_exception::archive_exception(boost::archive::archive_exception::exception_code, char const*, char const*)'
fmm_omp.cpp:(.text._ZN5boost7archive6detail15common_iarchiveINS0_15binary_iarchiveEE5vloadERNS0_13tracking_typeE[_ZN5boost7archive6detail15common_iarchiveINS0_15binary_iarchiveEE5vloadERNS0_13tracking_typeE]+0x71): undefined reference to `boost::archive::archive_exception::~archive_exception()'
CMakeFiles/fmm_omp.dir/app/fmm_omp.cpp.o: In function `boost::archive::detail::common_iarchive<boost::archive::binary_iarchive>::vload(boost::archive::object_id_type&)':
fmm_omp.cpp:(.text._ZN5boost7archive6detail15common_iarchiveINS0_15binary_iarchiveEE5vloadERNS0_14object_id_typeE[_ZN5boost7archive6detail15common_iarchiveINS0_15binary_iarchiveEE5vloadERNS0_14object_id_typeE]+0x5e): undefined reference to `boost::archive::archive_exception::archive_exception(boost::archive::archive_exception::exception_code, char const*, char const*)'
fmm_omp.cpp:(.text._ZN5boost7archive6detail15common_iarchiveINS0_15binary_iarchiveEE5vloadERNS0_14object_id_typeE[_ZN5boost7archive6detail15common_iarchiveINS0_15binary_iarchiveEE5vloadERNS0_14object_id_typeE]+0x71): undefined reference to `boost::archive::archive_exception::~archive_exception()'
CMakeFiles/fmm_omp.dir/app/fmm_omp.cpp.o: In function `boost::archive::detail::common_iarchive<boost::archive::binary_iarchive>::vload(boost::archive::class_id_type&)':
fmm_omp.cpp:(.text._ZN5boost7archive6detail15common_iarchiveINS0_15binary_iarchiveEE5vloadERNS0_13class_id_typeE[_ZN5boost7archive6detail15common_iarchiveINS0_15binary_iarchiveEE5vloadERNS0_13class_id_typeE]+0x2b): undefined reference to `boost::archive::detail::basic_iarchive::get_library_version() const'
fmm_omp.cpp:(.text._ZN5boost7archive6detail15common_iarchiveINS0_15binary_iarchiveEE5vloadERNS0_13class_id_typeE[_ZN5boost7archive6detail15common_iarchiveINS0_15binary_iarchiveEE5vloadERNS0_13class_id_typeE]+0xaa): undefined reference to `boost::archive::archive_exception::archive_exception(boost::archive::archive_exception::exception_code, char const*, char const*)'
fmm_omp.cpp:(.text._ZN5boost7archive6detail15common_iarchiveINS0_15binary_iarchiveEE5vloadERNS0_13class_id_typeE[_ZN5boost7archive6detail15common_iarchiveINS0_15binary_iarchiveEE5vloadERNS0_13class_id_typeE]+0xbd): undefined reference to `boost::archive::archive_exception::~archive_exception()'
fmm_omp.cpp:(.text._ZN5boost7archive6detail15common_iarchiveINS0_15binary_iarchiveEE5vloadERNS0_13class_id_typeE[_ZN5boost7archive6detail15common_iarchiveINS0_15binary_iarchiveEE5vloadERNS0_13class_id_typeE]+0xe0): undefined reference to `boost::archive::archive_exception::archive_exception(boost::archive::archive_exception::exception_code, char const*, char const*)'
CMakeFiles/fmm_omp.dir/app/fmm_omp.cpp.o:(.data.rel.ro._ZTIN5boost7archive6detail15common_iarchiveINS0_15binary_iarchiveEEE[_ZTIN5boost7archive6detail15common_iarchiveINS0_15binary_iarchiveEEE]+0x18): undefined reference to `typeinfo for boost::archive::detail::basic_iarchive'
collect2: error: ld returned 1 exit status
CMakeFiles/fmm_omp.dir/build.make:98: recipe for target 'fmm_omp' failed
make[2]: *** [fmm_omp] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/fmm_omp.dir/all' failed
make[1]: *** [CMakeFiles/fmm_omp.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by cyang-kth** [comment]
@xunhs 

It seems that your boost library is not found. The output of your cmake shows

```
-- Boost 1.54.0 found.
-- Found Boost components:
   serialization
-- Boost headers found at
-- Boost library found at Boost::serialization
```

That is also weird. Here it should print out some paths to boost header and library. 

On Mac it shows
```
-- GDAL headers found at /Library/Frameworks/GDAL.framework/Headers
-- GDAL library found at /Library/Frameworks/gdal.framework
-- Boost headers found at /usr/local/include
-- Boost library found at /usr/local/lib/libboost_serialization-mt.dylib
-- OpenMP_CXX_LIBRARIES found at /usr/local/lib/libomp.dylib
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/canyang/Workspace/fmm/build
```

On Win7 it shows
```
cmake ..
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++.exe
-- Check for working CXX compiler: /usr/bin/c++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found GDAL: /usr/lib/libgdal.dll.a (found suitable version "2.4.0", minimum required is "2.2")
-- GDAL headers found at /usr/include
-- GDAL library found at /usr/lib/libgdal.dll.a
-- Boost version: 1.66.0
-- Found the following Boost libraries:
--   serialization
-- Boost headers found at /usr/include
-- Boost library found at /usr/lib/libboost_serialization.dll.a
-- Found OpenMP_C: -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- OpenMP_CXX_LIBRARIES found at /usr/lib/gcc/x86_64-pc-cygwin/7.4.0/libgomp.dll.a
-- Configuring done
-- Generating done
-- Build files have been written to: /home/Administrator/workspace/fmm/build
```

**Comment by xunhs** [comment]
Emm. I'am sorry for closing this issue by no means. I have run that code `sudo apt-get install libboost-dev libboost-serialization-dev gdal-bin libgdal-dev make cmake` before `make`.  I don't know why the boost library is not found and how could I install boost library.

**Comment by cyang-kth** [comment]
@xunhs 

What is the output of this command:

```
sudo apt-get install libboost-dev libboost-serialization-dev gdal-bin libgdal-dev make cmake
```

It could be that the serialization package is not found on your system. 


Maybe you can try to run this command below to install the boost serialization package. 
```
sudo apt-get install libboost-all-dev
```

**Comment by xunhs** [comment]
This is the output of `sudo apt-get install libboost-dev libboost-serialization-dev gdal-bin libgdal-dev make cmake`:
```
Reading package lists... Done
Building dependency tree
Reading state information... Done
libboost-dev is already the newest version (1.65.1.0ubuntu1).
make is already the newest version (4.1-9.1ubuntu1).
libboost-serialization-dev is already the newest version (1.65.1.0ubuntu1).
cmake is already the newest version (3.10.2-1ubuntu2.18.04.1).
gdal-bin is already the newest version (2.4.2+dfsg-1~bionic0).
libgdal-dev is already the newest version (2.4.2+dfsg-1~bionic0).
0 upgraded, 0 newly installed, 0 to remove and 157 not upgraded.
```
It shows serialization package is installed.
After I run `sudo apt-get install libboost-all-dev` and `cmake`, 
```
-- GDAL headers found at /usr/include/gdal
-- GDAL library found at /usr/lib/libgdal.so
-- Boost 1.54.0 found.
-- Found Boost components:
   serialization
-- Boost headers found at
-- Boost library found at Boost::serialization
-- Found OpenMP_C: -fopenmp
-- Found OpenMP_CXX: -fopenmp
-- Found OpenMP: TRUE
-- OpenMP_CXX_LIBRARIES found at /usr/lib/gcc/x86_64-linux-gnu/7/libgomp.so;/usr/lib/x86_64-linux-gnu/libpthread.so
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/d/Workspace/TrajEmbedding/Environments/fmm-master/build
```
It seems  the serialization package is still not found. 
:(

**Comment by cyang-kth** [comment]
@xunhs 

I think the problem may be that your win system also have boost packages, which overwrites the path of boost in WSL. 

You may be able to try this cmakefile below which removes the finding boost package commands. 

[CMakeLists.txt](https://github.com/cyang-kth/fmm/files/4343808/CMakeLists.txt)

Then manually find the path of your installed boost headers and lib 
-- Boost headers found at /usr/include
-- Boost library found at /usr/lib/libboost_serialization.so
run your cmake with manual definition of the two paths of boost

```
cmake .. -DBoost_INCLUDE_DIR=/usr/include -DBoost_LIBRARIES=/usr/lib/libboost_serialization.so
make
```

If it does not work, I think you need to either run on a Ubuntu or try Cygwin.

**Comment by xunhs** [comment]
Hi, good news. I have built successfully on a Ubuntu 16.04. However, I have a small suggestion: before `Install requirements`, maybe we could run this codes:
```bash 
sudo add-apt-repository ppa:ubuntugis/ppa && sudo apt update
``` 
to upgrade gdal related packages :)
Here is my final output of `cmake ..`:
```
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found GDAL: /usr/lib/libgdal.so (Required is at least version "2.2") 
-- GDAL headers found at /usr/include/gdal
-- GDAL library found at /usr/lib/libgdal.so
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   serialization
-- Boost headers found at /usr/include
-- Boost library found at /usr/lib/x86_64-linux-gnu/libboost_serialization.so
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
-- OpenMP_CXX_LIBRARIES found at 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/only/Projects/fmm-master/build
```

Finally, thank for your great help and patience, it's really help me~~~ Thanks!
